# Generated by Django 3.1.5 on 2021-02-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_machine_spare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField(choices=[(1.0, 'Метры'), (0.3048, 'Футы'), (0.9144, 'Ярды')])),
            ],
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
